services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

volumes:
  pgdata: {}
