services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

  summer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: summer-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/app_db
      DB_USER: app
      DB_PASSWORD: mypassword
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

volumes:
  pgdata: {}
