services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}
